import type { Metadata } from "next";
import { ColorSchemeScript, createTheme, mantineHtmlProps, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import "./globals.css";


const theme = createTheme({
  /** Put your mantine theme override here */
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body
        className={`antialiased vsc-initialized`}
      >
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </body>
    </html>
  );
}
